using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Marvel_API.Models.ClassModels
{
    public class ChampionsModel
    {

            public int Id { get; set; }
            public ChampionModel Aatrox { get; set; }
            public ChampionModel Ahri { get; set; }
            public ChampionModel Akali { get; set; }
            public ChampionModel Alistar { get; set; }
            public ChampionModel Amumu { get; set; }
            public ChampionModel Anivia { get; set; }
            public ChampionModel Annie { get; set; }
            public ChampionModel Aphelios { get; set; }
            public ChampionModel Ashe { get; set; }
            public ChampionModel AurelionSol { get; set; }
            public ChampionModel Azir { get; set; }
            public ChampionModel Bard { get; set; }
            public ChampionModel Blitzcrank { get; set; }
            public ChampionModel Brand { get; set; }
            public ChampionModel Braum { get; set; }
            public ChampionModel Caitlyn { get; set; }
            public ChampionModel Camille { get; set; }
            public ChampionModel Cassiopeia { get; set; }
            public ChampionModel Chogath { get; set; }
            public ChampionModel Corki { get; set; }
            public ChampionModel Darius { get; set; }
            public ChampionModel Diana { get; set; }
            public ChampionModel DrMundo { get; set; }
            public ChampionModel Draven { get; set; }
            public ChampionModel Ekko { get; set; }
            public ChampionModel Elise { get; set; }
            public ChampionModel Evelynn { get; set; }
            public ChampionModel Ezreal { get; set; }
            public ChampionModel Fiddlesticks { get; set; }
            public ChampionModel Fiora { get; set; }
            public ChampionModel Fizz { get; set; }
            public ChampionModel Galio { get; set; }
            public ChampionModel Gangplank { get; set; }
            public ChampionModel Garen { get; set; }
            public ChampionModel Gnar { get; set; }
            public ChampionModel Gragas { get; set; }
            public ChampionModel Graves { get; set; }
            public ChampionModel Hecarim { get; set; }
            public ChampionModel Heimerdinger { get; set; }
            public ChampionModel Illaoi { get; set; }
            public ChampionModel Irelia { get; set; }
            public ChampionModel Ivern { get; set; }
            public ChampionModel Janna { get; set; }
            public ChampionModel JarvanIV { get; set; }
            public ChampionModel Jax { get; set; }
            public ChampionModel Jayce { get; set; }
            public ChampionModel Jhin { get; set; }
            public ChampionModel Jinx { get; set; }
            public ChampionModel KaiSa { get; set; }
            public ChampionModel Kalista { get; set; }
            public ChampionModel Karma { get; set; }
            public ChampionModel Karthus { get; set; }
            public ChampionModel Kassadin { get; set; }
            public ChampionModel Katarina { get; set; }
            public ChampionModel Kayle { get; set; }
            public ChampionModel Kayn { get; set; }
            public ChampionModel Kennen { get; set; }
            public ChampionModel Khazix { get; set; }
            public ChampionModel Kindred { get; set; }
            public ChampionModel Kled { get; set; }
            public ChampionModel KogMaw { get; set; }
            public ChampionModel LeBlanc { get; set; }
            public ChampionModel LeeSin { get; set; }
            public ChampionModel Leona { get; set; }
            public ChampionModel Lillia { get; set; }
            public ChampionModel Lissandra { get; set; }
            public ChampionModel Lucian { get; set; }
            public ChampionModel Lulu { get; set; }
            public ChampionModel Lux { get; set; }
            public ChampionModel Malphite { get; set; }
            public ChampionModel Malzahar { get; set; }
            public ChampionModel Maokai { get; set; }
            public ChampionModel MasterYi { get; set; }
            public ChampionModel MissFortune { get; set; }
            public ChampionModel Mordekaiser { get; set; }
            public ChampionModel Morgana { get; set; }
            public ChampionModel Nami { get; set; }
            public ChampionModel Nasus { get; set; }
            public ChampionModel Nautilus { get; set; }
            public ChampionModel Neeko { get; set; }
            public ChampionModel Nidalee { get; set; }
            public ChampionModel Nocturne { get; set; }
            public ChampionModel Nunu { get; set; }
            public ChampionModel Olaf { get; set; }
            public ChampionModel Orianna { get; set; }
            public ChampionModel Ornn { get; set; }
            public ChampionModel Pantheon { get; set; }
            public ChampionModel Poppy { get; set; }
            public ChampionModel Pyke { get; set; }
            public ChampionModel Qiyana { get; set; }
            public ChampionModel Quinn { get; set; }
            public ChampionModel Rakan { get; set; }
            public ChampionModel Rammus { get; set; }
            public ChampionModel RekSai { get; set; }
            public ChampionModel Rell { get; set; }
            public ChampionModel Renekton { get; set; }
            public ChampionModel Rengar { get; set; }
            public ChampionModel Riven { get; set; }
            public ChampionModel Rumble { get; set; }
            public ChampionModel Ryze { get; set; }
            public ChampionModel Samira { get; set; }
            public ChampionModel Sejuani { get; set; }
            public ChampionModel Senna { get; set; }
            public ChampionModel Seraphine { get; set; }
            public ChampionModel Sett { get; set; }
            public ChampionModel Shaco { get; set; }
            public ChampionModel Shen { get; set; }
            public ChampionModel Shyvana { get; set; }
            public ChampionModel Singed { get; set; }
            public ChampionModel Sion { get; set; }
            public ChampionModel Sivir { get; set; }
            public ChampionModel Skarner { get; set; }
            public ChampionModel Sona { get; set; }
            public ChampionModel Soraka { get; set; }
            public ChampionModel Swain { get; set; }
            public ChampionModel Sylas { get; set; }
            public ChampionModel Syndra { get; set; }
            public ChampionModel TahmKench { get; set; }
            public ChampionModel Taliyah { get; set; }
            public ChampionModel Talon { get; set; }
            public ChampionModel Taric { get; set; }
            public ChampionModel Teemo { get; set; }
            public ChampionModel Thresh { get; set; }
            public ChampionModel Tristana { get; set; }
            public ChampionModel Trundle { get; set; }
            public ChampionModel Tryndamere { get; set; }
            public ChampionModel TwistedFate { get; set; }
            public ChampionModel Twitch { get; set; }
            public ChampionModel Udyr { get; set; }
            public ChampionModel Urgot { get; set; }
            public ChampionModel Varus { get; set; }
            public ChampionModel Vayne { get; set; }
            public ChampionModel Veigar { get; set; }
            public ChampionModel VelKoz { get; set; }
            public ChampionModel Vi { get; set; }
            public ChampionModel Viego { get; set; }
            public ChampionModel Viktor { get; set; }
            public ChampionModel Vladimir { get; set; }
            public ChampionModel Volibear { get; set; }
            public ChampionModel Warwick { get; set; }
            public ChampionModel MonkeyKing { get; set; }
            public ChampionModel Xayah { get; set; }
            public ChampionModel Xerath { get; set; }
            public ChampionModel XinZhao { get; set; }
            public ChampionModel Yasuo { get; set; }
            public ChampionModel Yone { get; set; }
            public ChampionModel Yorick { get; set; }
            public ChampionModel Yuumi { get; set; }
            public ChampionModel Zac { get; set; }
            public ChampionModel Zed { get; set; }
            public ChampionModel Ziggs { get; set; }
            public ChampionModel Zilean { get; set; }
            public ChampionModel Zoe { get; set; }
            public ChampionModel Zyra { get; set; }

        }
    }

